import type { EventSubscription } from 'expo-modules-core';

import HubspotChatModule from './HubspotChatModule';
import type {
  HubspotChatProperties,
  HubspotChatEvent,
  OpenChatOptions,
} from './HubspotChat.types';

export type {
  HubspotUserIdentity,
  HubspotChatProperties,
  HubspotChatPresentationStyle,
  OpenChatOptions,
  HubspotChatEvent,
  HubspotChatEventType,
} from './HubspotChat.types';

let _initialized = false;

const NOT_INITIALIZED_WARNING =
  '[expo-hubspot-chat] SDK not initialized. Call initialize() first.';

/**
 * Initialize the HubSpot Chat SDK. Must be called once before any other method.
 *
 * Configuration (portalId, hublet, environment) is read from the native config
 * files generated by the Expo config plugin. See the README for setup instructions.
 *
 * @example
 * ```ts
 * import { initialize } from 'expo-hubspot-chat';
 *
 * initialize();
 * ```
 */
export function initialize(): void {
  HubspotChatModule.initialize();
  _initialized = true;
}

/**
 * Returns whether `initialize()` has been called.
 */
export function isInitialized(): boolean {
  return _initialized;
}

/**
 * Identify the current user for the chat session.
 * The `identityToken` should be generated server-side using HubSpot's
 * [Visitor Identification API](https://developers.hubspot.com/docs/api/conversation/visitor-identification).
 *
 * @param email - User's email address
 * @param identityToken - Server-generated identity verification token
 */
export function setUserIdentity(email: string, identityToken: string): void {
  if (!_initialized) {
    console.warn(NOT_INITIALIZED_WARNING);
    return;
  }
  HubspotChatModule.setUserIdentity(email, identityToken);
}

/**
 * Open the HubSpot chat UI.
 *
 * @param options - Optional chat flow and presentation style
 *
 * @example
 * ```ts
 * // Open with default chat flow (from plugin config)
 * openChat();
 *
 * // Open a specific chat flow
 * openChat({ chatFlow: 'billing' });
 *
 * // iOS: open as full screen modal
 * openChat({ chatFlow: 'support', presentationStyle: 'fullScreen' });
 * ```
 */
export function openChat(options?: OpenChatOptions | string): void {
  if (!_initialized) {
    console.warn(NOT_INITIALIZED_WARNING);
    return;
  }
  if (typeof options === 'string') {
    HubspotChatModule.openChat(options, null);
    return;
  }
  HubspotChatModule.openChat(
    options?.chatFlow ?? null,
    options?.presentationStyle ?? null,
  );
}

/**
 * Programmatically close the chat UI.
 */
export function closeChat(): void {
  if (!_initialized) {
    console.warn(NOT_INITIALIZED_WARNING);
    return;
  }
  HubspotChatModule.closeChat();
}

/**
 * Set custom properties on the chat session.
 * Properties are key-value string pairs visible to HubSpot agents.
 *
 * @example
 * ```ts
 * setChatProperties({
 *   'user-name': 'Jane Doe',
 *   'plan': 'enterprise',
 * });
 * ```
 */
export function setChatProperties(properties: HubspotChatProperties): void {
  if (!_initialized) {
    console.warn(NOT_INITIALIZED_WARNING);
    return;
  }
  HubspotChatModule.setChatProperties(properties);
}

/**
 * Clear the current user's data and end their chat session.
 * Call this on sign-out to prevent data leaking between users.
 */
export async function clearUser(): Promise<void> {
  await HubspotChatModule.clearUser();
}

/**
 * Subscribe to chat lifecycle events.
 *
 * @returns An `EventSubscription` that should be removed when no longer needed.
 *
 * @example
 * ```ts
 * const subscription = addChatEventListener((event) => {
 *   if (event.type === 'chatClosed') {
 *     console.log('User closed the chat');
 *   }
 * });
 *
 * // Later: cleanup
 * subscription.remove();
 * ```
 */
export function addChatEventListener(
  listener: (event: HubspotChatEvent) => void,
): EventSubscription {
  return HubspotChatModule.addListener('onHubspotChatEvent', listener);
}
